//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerShopInfo
    {
        public long Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int ShopId { get; set; }
        public string TeamLeaderName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public Nullable<int> UploadUserId { get; set; }
    }
}
