//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.SurveyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerLog
    {
        public long AnswerIdLogId { get; set; }
        public Nullable<long> AnswerId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<decimal> PhotoScore { get; set; }
        public string PhotoScoreResult { get; set; }
        public string InspectionStandardResult { get; set; }
        public string FileResult { get; set; }
        public string LossResult { get; set; }
        public string LossResultAdd { get; set; }
        public string ShopConsultantResult { get; set; }
        public string Remark { get; set; }
        public string DataStatus { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string TranStatus { get; set; }
    }
}
