//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.SurveyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerShopConsultantScore
    {
        public long AnswerShopConsultantScoreId { get; set; }
        public Nullable<long> AnswerId { get; set; }
        public Nullable<long> ConsultantId { get; set; }
        public Nullable<decimal> ConsultantScore { get; set; }
        public string ConsultantLossDesc { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
