//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppealFile
    {
        public int FileId { get; set; }
        public Nullable<int> AppealId { get; set; }
        public int SeqNO { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string ServerFileName { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
    }
}
