//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int AppealId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopCode { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string SubjectCode { get; set; }
        public string CheckPoint { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string LossResult { get; set; }
        public string AppealReason { get; set; }
        public Nullable<int> AppealUserId { get; set; }
        public Nullable<System.DateTime> AppealDateTime { get; set; }
        public string FeedBackStatus { get; set; }
        public string FeedBackReason { get; set; }
        public Nullable<int> FeedBackUserId { get; set; }
        public Nullable<System.DateTime> FeedBackDateTime { get; set; }
        public string ShopAcceptStatus { get; set; }
        public string ShopAcceptReason { get; set; }
        public Nullable<int> ShopAcceptUserId { get; set; }
        public Nullable<System.DateTime> ShopAcceptDateTime { get; set; }
    }
}
