//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReCheck
    {
        public int RecheckId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int ShopId { get; set; }
        public int SubjectId { get; set; }
        public Nullable<bool> PassReCheck { get; set; }
        public string ReCheckContent { get; set; }
        public string RecheckError { get; set; }
        public Nullable<int> ReCheckUserId { get; set; }
        public Nullable<System.DateTime> RecheckDateTime { get; set; }
        public Nullable<bool> AgreeCheck { get; set; }
        public string AgreeReason { get; set; }
        public Nullable<int> AgreeUserId { get; set; }
        public Nullable<System.DateTime> AgreeDateTime { get; set; }
        public Nullable<bool> LastConfirmCheck { get; set; }
        public string LastConfirmReason { get; set; }
        public Nullable<int> LastConfirmUserId { get; set; }
        public Nullable<System.DateTime> LastConfirmDate { get; set; }
    }
}
