//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<DeleteFileLog> DeleteFileLog { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectShop> ProjectShop { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopSubjectTypeExam> ShopSubjectTypeExam { get; set; }
        public virtual DbSet<SubjectFile> SubjectFile { get; set; }
        public virtual DbSet<SubjectInspectionStandard> SubjectInspectionStandard { get; set; }
        public virtual DbSet<SubjectLossResult> SubjectLossResult { get; set; }
        public virtual DbSet<SubjectRecheckType> SubjectRecheckType { get; set; }
        public virtual DbSet<SubjectType> SubjectType { get; set; }
        public virtual DbSet<SubjectTypeExam> SubjectTypeExam { get; set; }
        public virtual DbSet<SubjectTypeScoreRegion> SubjectTypeScoreRegion { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<UserInfoBrand> UserInfoBrand { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<AnswerShopInfo> AnswerShopInfo { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AnswerShopConsultant> AnswerShopConsultant { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SubjectLink> SubjectLink { get; set; }
    }
}
